Feature/global font to onest #5
dedivoevali/myBlog pull request #17
Opened 2023-10-14 14:20 UTC by AyanoNakahara

2023-10-14 15:58 UTC, chioroglo requested changes
Please put fonts in src/shared/assets/fonts

2023-10-14 15:58 UTC, chioroglo commented on React/my-blog/src/App.css
> +    font-family: 'Onest' !important;
Have you checked how it affects other parts of application? F.e if I want to change my font locally to Roboto, wouldn't this construction override my font to Onest?

2023-10-14 16:32 UTC, AyanoNakahara commented on React/my-blog/src/App.css
> +    font-family: 'Onest' !important;
Should the other local fonts be erased then for now? or not?

2023-10-14 16:37 UTC, AyanoNakahara commented
Changed folder for fonts

2023-10-15 16:56 UTC, chioroglo commented on React/my-blog/src/App.css
> +    font-family: 'Onest' !important;
I mean, that what you've done would override this font all over components (because of an asterisk alias), both React ones and both native HTML ones, it's not so good approach because it'd be difficult to override what cannot be overriden ("!important"). I have attached this to a configurable theme of Material UI.

2023-10-15 16:57 UTC, chioroglo commented
thank you so much

2023-10-15 16:57 UTC, chioroglo approved these changes

2023-10-15 18:41 UTC, merged